# Generated by Django 6.0.7 on 2026-07-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
    ]
